# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-12 17:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0004_remove_messages_edited_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Twit',
            new_name='Tweet',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='twit',
            new_name='tweet',
        ),
    ]
